server:
  port: 9000
  servlet:
    context-path: /accounts
  error:
    include-binding-errors: always
    include-stacktrace: on_param
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
springdoc:
  swagger-ui:
    path: /api-docs

accounts:
  message: Hello World I am Here
  contactDetails:
    name: Richard
    email: enuazubike88@gmail.com
